site_name: Kubr
repo_url: https://github.com/alex-kharlamov/KubeResearch
repo_name: KubeResearch
site_author: Alex Kharlamov

plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
#    custom_templates: templates
    default_handler: python
    handlers:
      python:
        paths: [.]
        options:
          docstring_style: google
          show_root_heading: true
#          merge_init_into_class: true
#          show_submodules: true

markdown_extensions:
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true


watch:
  - kubr/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections

nav:
  - "Config": config.md